---
title: "STA304_Final_Project"
author: "Yubing Xia"
date: "2020/12/10"
output: pdf_document
---

```{r setup, include=FALSE}
##Import data into R
#Before raw data input, the variable "p_stable_food" was renamed to "Pstable_food" in csv file to avoid double hyphen.
dataFood<-read.csv('/Users/gsh/Desktop/STA304_Final_Project/predicting_food_crises_data.csv', header = T)
dataFood
attach(dataFood)

```


```{r cars}
##recode the outcome variable to categorical
library(dplyr)
dataFood$centy2<-cut(dataFood$centy, breaks=c(-26,0,38), labels =c(1,0))
dataFood$centy3<-na.omit(dataFood$centy2)
table(dataFood$centy3)
```

## Plots
```{r pressure, echo=FALSE}
# the plot is not generated from this R code because of the `echo = FALSE` parameter.
##fit a logistic model with all the factors
mylogit <- glm(dataFood$centy2~centx + et_mean+Pstaple_food+cropland_pct+pasture_pct+dataFood$area, family = binomial(link = "logit"))
summary(mylogit)
```

```{r}
##using backward elimination method, the following model was fitted
mylogit1 <- glm(dataFood$centy2~centx + et_mean+Pstaple_food+pasture_pct, family = binomial(link = "logit"))
summary(mylogit1)
```
```{r}
##diagnostic checking of the model
resid<-rstandard(mylogit1)
Normalplot<-qqnorm(resid, 
                   ylab = "Standardized residuals",
                   xlab = "Normal scores",
                   main = "Normal probability plot")
qqline(resid)
```
```{r}
##predicting the probabilities
pred_prob <- predict(mylogit1, dataFood, type = "response")
pred_prob
##we display the first 100 predicted probabilities
pred_prob[1:100]
```

*Reference*
Afghanistan, Burkina Faso et al. Predicting Food Crises 2020, Dataset for Reproducing Working Paper Results. The World Bank, 2020. 
https://microdata.worldbank.org/index.php/catalog/3811/data-dictionary/F1?file_name=predicting_food_crises_data
